DROP TABLE IF EXISTS friends cascade;
DROP TABLE IF EXISTS films_genres cascade;
DROP TABLE IF EXISTS films_likes cascade;
DROP TABLE IF EXISTS users cascade;
DROP TABLE IF EXISTS genre cascade;
DROP TABLE IF EXISTS films cascade;
DROP TABLE IF EXISTS mpa cascade;

CREATE TABLE IF NOT EXISTS mpa (
                                   id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   name varchar
);

CREATE TABLE IF NOT EXISTS genre (
                                     id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     name varchar
);

CREATE TABLE IF NOT EXISTS users  (
                                      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      email varchar NOT NULL,
                                      login varchar NOT NULL,
                                      name varchar NOT NULL,
                                      birthday date NOT NULL
);

CREATE TABLE IF NOT EXISTS films (
                                     id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     name varchar,
                                     description varchar,
                                     release_date date,
                                     duration int,
                                     mpa_id bigint,
                                     CONSTRAINT fk_film_mpa_id FOREIGN KEY(mpa_id) REFERENCES mpa (id) ON DELETE CASCADE


);

CREATE TABLE IF NOT EXISTS friends (
                                       user_id bigint,
                                       friend_id bigint,
                                       is_confirmed boolean,
                                       CONSTRAINT pk_friends PRIMARY KEY (user_id, friend_id),
                                       CONSTRAINT fk_friends_user_id FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE,
                                       CONSTRAINT fk_friends_friend_id FOREIGN KEY(friend_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS film_genres (
                                           film_id bigint,
                                           genre_id bigint,
                                           CONSTRAINT pk_films_genres PRIMARY KEY (film_id, genre_id),
                                           CONSTRAINT fk_films_genres_film_id FOREIGN KEY(film_id) REFERENCES films (id) ON DELETE CASCADE,
                                           CONSTRAINT fk_films_genres_genre_id FOREIGN KEY(genre_id) REFERENCES genre (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS film_likes (
                                          film_id bigint,
                                          user_id bigint,
                                          CONSTRAINT pk_films_likes PRIMARY KEY (film_id, user_id),
                                          CONSTRAINT fk_films_likes_film_id FOREIGN KEY(film_id) REFERENCES films (id) ON DELETE CASCADE,
                                          CONSTRAINT fk_films_likes_user_id FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);